packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@ark-ui/react": ^5.36.1
  "@ark-ui/vue": ^5.36.1
  "@types/node": ^24
  "@vitepress-demo-preview/component": ^2.6.2
  "@vitepress-demo-preview/plugin": ^1.4.1
  "@whyframe/core": ^0.1.14
  "@whyframe/vue": ^0.1.9
  style-dictionary: ^5.4.0
  tsx: ^4.21.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitepress: ^1.6.4
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: ^3.5.30

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
