// Public surface of @espresso-ui/tokens.
// The actual CSS output lives in dist/primitives.css, dist/tokens.css,
// and dist/tailwind.css — generated by sd.config.ts via Style Dictionary.

import primitivesJson from "./primitives.json" with { type: "json" };
import semanticJson from "./semantic.json" with { type: "json" };

export interface Primitives {
  color: Record<string, Record<string, string>>;
  spacing: Record<string, string>;
  radius: Record<string, string>;
  font: {
    family: Record<string, string>;
    size: Record<string, string>;
    weight: Record<string, string>;
    "line-height": Record<string, string>;
    "letter-spacing": Record<string, string>;
  };
  shadow: Record<string, string>;
}

export interface SemanticSection {
  color: Record<string, string>;
  shadow: Record<string, string>;
}

export interface Semantic {
  light: SemanticSection;
  dark: SemanticSection;
  radius: Record<string, string>;
}

export const primitives = primitivesJson as unknown as Primitives;
export const semantic = semanticJson as unknown as Semantic;

/** Semantic color token names (matches the CSS custom properties in tokens.css). */
export type SemanticColorToken =
  | "color-background"
  | "color-foreground"
  | "color-card"
  | "color-card-foreground"
  | "color-popover"
  | "color-popover-foreground"
  | "color-primary"
  | "color-primary-foreground"
  | "color-secondary"
  | "color-secondary-foreground"
  | "color-muted"
  | "color-muted-foreground"
  | "color-accent"
  | "color-accent-foreground"
  | "color-destructive"
  | "color-destructive-foreground"
  | "color-border"
  | "color-input"
  | "color-ring"
  | "color-info"
  | "color-info-foreground"
  | "color-info-subtle"
  | "color-success"
  | "color-success-foreground"
  | "color-success-subtle"
  | "color-warning"
  | "color-warning-foreground"
  | "color-warning-subtle"
  | "color-error"
  | "color-error-foreground"
  | "color-error-subtle"
  | "color-ink-1"
  | "color-ink-2"
  | "color-ink-3"
  | "color-ink-4"
  | "color-ink-5"
  | "color-line"
  | "color-line-2"
  | "color-surface"
  | "color-surface-2"
  | "color-surface-3";

/** Semantic shadow token names. */
export type SemanticShadowToken =
  | "shadow-sm"
  | "shadow-base"
  | "shadow-md"
  | "shadow-lg"
  | "shadow-xl"
  | "shadow-2xl";

/** Semantic radius token names. */
export type SemanticRadiusToken =
  | "radius-sm"
  | "radius-md"
  | "radius-lg"
  | "radius-xl"
  | "radius-2xl"
  | "radius-3xl"
  | "radius-full";

/** Union of all semantic token names. */
export type SemanticToken = SemanticColorToken | SemanticShadowToken | SemanticRadiusToken;

/** Returns a CSS var reference string, e.g. cssVar("color-primary") → "var(--color-primary)". */
export function cssVar(token: SemanticToken): string {
  return `var(--${token})`;
}
